### ISSUE TITLE
Demo doesn't seem to work?

### ISSUE THREAD

**Issue by njt1982** [englercj/gl-tiled#2]
On Chrome 66 and Firefox 59 (on OSX Sierra)... all latest versions... I get this:

![image](https://user-images.githubusercontent.com/384976/39420356-13f5780a-4c5c-11e8-90ab-89680ba1319b.png)

Nothing obviously wrong in the Network or Console tabs though?

This is the data layer:
![image](https://user-images.githubusercontent.com/384976/39420387-427423f2-4c5c-11e8-9439-d7b4115e9e4f.png)

**Comment by englercj** [comment]
Is currently working with those same versions for me on Windows. I don't have a Mac to test OSX with though.

Those data layers seem correct. I'm using a nVidia GTX 1070

**Comment by karreiro** [comment]
I just tested it on Chrome (66.0.3359.139), in a macOS (with an Intel Iris Pro) and I could not reproduce the problem too:
<img width="1704" alt="screen shot 2018-05-15 at 9 16 10 pm" src="https://user-images.githubusercontent.com/1079279/40090025-7c9c61ea-5885-11e8-8881-f50a10271fc4.png">

**Comment by njt1982** [comment]
I just tried it again. Same thing on Chrome 66, Firefox 60 and Safari 11.1.

I'm running OSX Sierra (10.13.4) on an i7 MacBook Pro which has a AMD Radeon R9 M370X 2Gb graphics.

![image](https://user-images.githubusercontent.com/384976/40108793-e4dd0214-58f3-11e8-8870-4290d507a20f.png)

It also has an "Intel Iris Pro" (like you @karreiro ) - but it's not using it at the moment as I have an external screen plugged in.

**Comment by njt1982** [comment]
I've tried unplugging the external screen and putting it on battery to try to force it down to the Intel chip, but it doesn't appears to be switching, so I assume I have an app running which is stopping it going to the Intel chip.

**Comment by englercj** [comment]
Going to have to assume this is an issue with WebGL on the specific hardware/platform this bug was happening on. If we can get more details or someone can debug when they see the error we can hopefully do better.

**Comment by njt1982** [comment]
Doesn't work on Chrome 80 on Windows 10.

```
Uncaught TypeError: Cannot read property 'imageMetadata' of undefined
    at Loader.tiledMiddleware (gl-tiled.resource-loader.js:48)
    at resource-loader.js:1120
    at resource-loader.js:915
```

(This is on an entirely different system to the one I used in 2018; this one is an i7 desktop with a nvidia 780Ti)

**Comment by njt1982** [comment]
Also didn't work in Edge either

**Comment by englercj** [comment]
That is a new error unrelated to the original post here. I'm in the middle of doing some updates to the lib and haven't touched the tests yet.

**Edit:** Fixed now.
