### ISSUE TITLE
How to rotate tilemap?

### ISSUE THREAD

**Issue by agoncharovdev** [englercj/gl-tiled#3]
Thank you for huge work. I saw, there are couple of methods setAxisAngle and rotationTo, but I have not clue how to use them. Please, can you help with that. Thank you!

**Comment by englercj** [comment]
I'm not sure which methods you are referring to, there are no such functions in this library.

Are you trying to rotate specific tiles, or rotate an entire layer? The former is supported and the rotation is done in Tiled, the later is not supported.

**Comment by englercj** [comment]
Closing this, I think this was in the wrong repo.
