### ISSUE TITLE
Animated Tiles causes the tiles to be a solid color

### ISSUE THREAD

**Issue by EvieMae** [englercj/gl-tiled#6]
![image](https://user-images.githubusercontent.com/24654131/76011171-09fc5700-5f0c-11ea-8834-85f8c8fcba11.png)
This is the tilesheet I'm using. 
[mapjson.txt](https://github.com/englercj/gl-tiled/files/4294376/mapjson.txt)

![image](https://user-images.githubusercontent.com/24654131/76011256-2b5d4300-5f0c-11ea-9509-2662b5642fee.png)
That is what it looks like before I animate the tiles.

What it looks like in tiled. ![image](https://i.gyazo.com/f32aba578d9671b7f04bd7d43e35beca.gif)

In the browser,

![image](https://user-images.githubusercontent.com/24654131/76011522-a58dc780-5f0c-11ea-8942-631b39dda3ad.png)

**Comment by englercj** [comment]
Do you have a running sample I can debug?

**Comment by EvieMae** [comment]
Do you have anything I can send it over

**Comment by EvieMae** [comment]
Sorry for the disjointed file format, haven't cleaned it and simplified it yet. 

https://github.com/theopathy/Dusk/tree/animatedtilestest

https://github.com/theopathy/Dusk/blob/animatedtilestest/projects/Ikimono/Ikimono.runtime.js -- Game Js

https://github.com/theopathy/Dusk/blob/animatedtilestest/js/core_runtime.js#L126

Thanks again, let me know if you need and further stuff or explanations, thank you.

**Comment by englercj** [comment]
I'll do my best to take a look this weekend. Thanks!

**Comment by EvieMae** [comment]
Is there anything wrong, that I could be missing like image type or certain aspect ratios, thank you

**Comment by englercj** [comment]
How do I turn on the animation to reproduce your issue? It is just rendering the non-animated version for me.

**Comment by englercj** [comment]
OK I added the animation to the map manually and can repro the issue, looking into it now.

**Comment by englercj** [comment]
Oh your version is old. I upgraded to the latest, and added a `tilemap.update` call and everything works as expected.

**Comment by EvieMae** [comment]
Didnt wanna make a new issue but how do I compile the TS to Js, thank you.

**Comment by englercj** [comment]
`npm install && npm run build`

**Comment by EvieMae** [comment]
No matter what I do, it doesn't work in my project only the built project and I've copied all the code over

**Comment by EvieMae** [comment]
Got it working nvm, I was being stupid
